// lib/demo.ts
export const DEMO_JOBS = [
  {
    id: "demo-1",
    title: "Master Barber (Walk-ins)",
    role: "barber",
    compModel: "commission",
    payVisible: true,
    payMin: 45,
    payUnit: "%",
    employmentType: "w2",
    schedule: "full_time",
    experienceText: "3+ Years",
    employerProfile: { shopName: "Fade Factory" },
    location: { city: "San Diego", state: "CA", lat: 32.7157, lng: -117.1611 },
    photos: [{ url: "https://images.unsplash.com/photo-1517836357463-d25dfeac3438?q=80&w=800&auto=format&fit=crop" }],
    createdAt: new Date().toISOString(),
  },
  {
    id: "demo-2",
    title: "Tattoo Artist — Black & Grey",
    role: "tattoo_artist",
    compModel: "booth_rent",
    payVisible: true,
    payMin: 900,
    payUnit: "$/wk",
    employmentType: "c1099",
    schedule: "full_time",
    experienceText: "Portfolio Required",
    employerProfile: { shopName: "Luna Ink Studio" },
    location: { city: "North Park", state: "CA", lat: 32.7473, lng: -117.1297 },
    photos: [{ url: "https://images.unsplash.com/photo-1542037104857-ffbb0b9155fb?q=80&w=800&auto=format&fit=crop" }],
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 3).toISOString(),
  },
  {
    id: "demo-3",
    title: "Nail Tech — Gel/X",
    role: "nail_tech",
    compModel: "hourly",
    payVisible: true,
    payMin: 25,
    payUnit: "$/hr",
    employmentType: "w2",
    schedule: "part_time",
    experienceText: "1–2 Years",
    employerProfile: { shopName: "Polish & Co." },
    location: { city: "La Jolla", state: "CA", lat: 32.8328, lng: -117.2713 },
    photos: [{ url: "https://images.unsplash.com/photo-1522335789203-aabd1fc54bc9?q=80&w=800&auto=format&fit=crop" }],
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 8).toISOString(),
  },
  {
    id: "demo-4",
    title: "Lash Tech — Volume Sets",
    role: "lash_tech",
    compModel: "hybrid",
    payVisible: true,
    payMin: 30,
    payMax: 22,
    payUnit: "$/hr",
    employmentType: "c1099",
    schedule: "part_time",
    experienceText: "Apprentices OK",
    employerProfile: { shopName: "Blink Bar" },
    location: { city: "Hillcrest", state: "CA", lat: 32.748, lng: -117.161 },
    photos: [{ url: "https://images.unsplash.com/photo-1582092723681-5b3c5f3c0b9a?q=80&w=800&auto=format&fit=crop" }],
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 12).toISOString(),
  },
  {
    id: "demo-5",
    title: "Professional Piercer",
    role: "piercer",
    compModel: "hourly",
    payVisible: true,
    payMin: 32,
    payUnit: "$/hr",
    employmentType: "c1099",
    schedule: "full_time",
    experienceText: "5+ Years",
    employerProfile: { shopName: "Seaport Piercing" },
    location: { city: "Seaport Village", state: "CA", lat: 32.708, lng: -117.171 },
    photos: [{ url: "https://images.unsplash.com/photo-1556229080-5f3e78f2458b?q=80&w=800&auto=format&fit=crop" }],
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 2).toISOString(),
  },
];
